const PREFIX = '@@realisation/';

export enum RealisationActionTypes {
  API_RESPONSE_SUCCESS = `${PREFIX}API_RESPONSE_SUCCESS`,
  API_RESPONSE_ERROR   = `${PREFIX}API_RESPONSE_ERROR`,

  LOAD_MY_REALISATIONS = `${PREFIX}LOAD_MY_REALISATIONS`,
  CREATE_REALISATION   = `${PREFIX}CREATE_REALISATION`,
  UPDATE_REALISATION   = `${PREFIX}UPDATE_REALISATION`,
  DELETE_REALISATION   = `${PREFIX}DELETE_REALISATION`,

  // UI
  SELECT_REALISATION   = `${PREFIX}SELECT_REALISATION`,
  OPEN_FORM            = `${PREFIX}OPEN_FORM`,
  CLOSE_FORM           = `${PREFIX}CLOSE_FORM`,
  CLEAR_MSG            = `${PREFIX}CLEAR_MSG`,
}