const PREFIX = '@@collaborator/';

export enum CollaboratorActionTypes {
  API_RESPONSE_SUCCESS = `${PREFIX}API_RESPONSE_SUCCESS`,
  API_RESPONSE_ERROR   = `${PREFIX}API_RESPONSE_ERROR`,

  GET_ME             = `${PREFIX}GET_ME`,
  ADD_SKILL          = `${PREFIX}ADD_SKILL`,
  UPDATE_SKILL       = `${PREFIX}UPDATE_SKILL`,
  DELETE_SKILL       = `${PREFIX}DELETE_SKILL`,
  ADD_EXPERIENCE     = `${PREFIX}ADD_EXPERIENCE`,
  UPDATE_EXPERIENCE  = `${PREFIX}UPDATE_EXPERIENCE`,
  DELETE_EXPERIENCE  = `${PREFIX}DELETE_EXPERIENCE`,
  ADD_EDUCATION      = `${PREFIX}ADD_EDUCATION`,
  UPDATE_EDUCATION   = `${PREFIX}UPDATE_EDUCATION`,
  DELETE_EDUCATION   = `${PREFIX}DELETE_EDUCATION`,
  ADD_CERTIFICATION  = `${PREFIX}ADD_CERTIFICATION`,
  UPDATE_CERTIFICATION = `${PREFIX}UPDATE_CERTIFICATION`,
  DELETE_CERTIFICATION = `${PREFIX}DELETE_CERTIFICATION`,
  ADD_PROJECT        = `${PREFIX}ADD_PROJECT`,
  UPDATE_PROJECT     = `${PREFIX}UPDATE_PROJECT`,
  DELETE_PROJECT     = `${PREFIX}DELETE_PROJECT`,
  CLEAR_MSG          = `${PREFIX}CLEAR_MSG`,
}