const PREFIX = '@@shortlist/';

export enum ShortlistActionTypes {
  API_RESPONSE_SUCCESS = `${PREFIX}API_RESPONSE_SUCCESS`,
  API_RESPONSE_ERROR   = `${PREFIX}API_RESPONSE_ERROR`,

  // Manager CRUD
  CREATE_SHORTLIST     = `${PREFIX}CREATE_SHORTLIST`,
  LOAD_MY_SHORTLISTS   = `${PREFIX}LOAD_MY_SHORTLISTS`,
  LOAD_SHORTLIST       = `${PREFIX}LOAD_SHORTLIST`,
  UPDATE_SHORTLIST     = `${PREFIX}UPDATE_SHORTLIST`,
  DELETE_SHORTLIST     = `${PREFIX}DELETE_SHORTLIST`,
  SEND_SHORTLIST       = `${PREFIX}SEND_SHORTLIST`,

  // Items
  ADD_ITEM             = `${PREFIX}ADD_ITEM`,
  REMOVE_ITEM          = `${PREFIX}REMOVE_ITEM`,

  // Client view
  VIEW_BY_TOKEN        = `${PREFIX}VIEW_BY_TOKEN`,

  // UI
  SET_SELECTED         = `${PREFIX}SET_SELECTED`,
  CLEAR_MSG            = `${PREFIX}CLEAR_MSG`,
  OPEN_BUILDER         = `${PREFIX}OPEN_BUILDER`,
  CLOSE_BUILDER        = `${PREFIX}CLOSE_BUILDER`,
}